### ISSUE TITLE
Doesn't build with go-1.1

### ISSUE THREAD

**Issue by pwaller** [kisielk/errcheck#18]
```
fractal ~/.local/src/github.com/kisielk/errcheck 24085 [:c061276|✔] 
01:20 :) go build
# github.com/kisielk/errcheck
./main.go:201: cannot use fset (type *token.FileSet) as type string in function argument
./main.go:201: cannot use astFiles (type []*ast.File) as type *token.FileSet in function argument
./main.go:255: obj.GetPkg undefined (type types.Object has no field or method GetPkg)
./main.go:267: undefined: types.NamedType
./main.go:269: t.Obj undefined (type types.Type has no field or method Obj)
./main.go:272: undefined: types.Result
./main.go:274: t.Values undefined (type types.Type has no field or method Values)
./main.go:367: cannot use pkg.Path (type func() string) as type string in map index
./main.go:368: cannot use pkg.Path (type func() string) as type string in map index
./main.go:374: invalid operation: pkg != nil && pkg.Complete (mismatched types bool and func() bool)
./main.go:374: too many errors
fractal ~/.local/src/github.com/kisielk/errcheck 24086 [:c061276|✔] 
01:20 :(
```
