### ISSUE TITLE
Does not build on Go 1.6

### ISSUE THREAD

**Issue by serejja** [kisielk/errcheck#94]
Just tried to go get this package with Go 1.6 and got the following:

```
>> go get github.com/kisielk/errcheck
# github.com/kisielk/errcheck/internal/errcheck
../../../kisielk/errcheck/internal/errcheck/errcheck.go:234: impossible type switch case: v.pkg.Info.Types[call].Type (type "golang.org/x/tools/go/types".Type) cannot have dynamic type *"go/types".Named (wrong type for Underlying method)
	have Underlying() "go/types".Type
	want Underlying() "golang.org/x/tools/go/types".Type
../../../kisielk/errcheck/internal/errcheck/errcheck.go:237: impossible type switch case: v.pkg.Info.Types[call].Type (type "golang.org/x/tools/go/types".Type) cannot have dynamic type *"go/types".Pointer (wrong type for Underlying method)
	have Underlying() "go/types".Type
	want Underlying() "golang.org/x/tools/go/types".Type
../../../kisielk/errcheck/internal/errcheck/errcheck.go:240: impossible type switch case: v.pkg.Info.Types[call].Type (type "golang.org/x/tools/go/types".Type) cannot have dynamic type *"go/types".Tuple (wrong type for Underlying method)
	have Underlying() "go/types".Type
	want Underlying() "golang.org/x/tools/go/types".Type
../../../kisielk/errcheck/internal/errcheck/errcheck.go:275: impossible type assertion:
	*"go/types".Builtin does not implement "golang.org/x/tools/go/types".Object (wrong type for Parent method)
		have Parent() *"go/types".Scope
		want Parent() *"golang.org/x/tools/go/types".Scope
```

Any chance to get this fixed soon? Thanks!

**Comment by serejja** [comment]
Ok, worked fine with `go get -u` :)
